const topics = [
	"Technology",
	"Computer",
	"Wonder Of Science",
	"Mobile Phone",
	"Internet",
	"Newspaper",
	"Diwali",
	"Independence Day (15 August)",
	"Holi",
	"Teachers Day",
	"Summer Vacation",
	"Christmas",
	"Children’s Day",
	"Swachh Bharat Abhiyan",
	"Durga Puja",
	"Janmashtami",
	"Republic Day",
	"Education",
	"Importance of Education",
	"Education should be free",
	"Contribution of Technology in Education",
];

const communities = [
	"Make Money Online",
	"Finance",
	"Travel",
	"Fitness",
	"Personal Development",
	"Relationships",
	"Lifestyle",
	"Real Estate",
	"Gadgets And Technology",
	"Food",
	"Entertainment",
	"Pets",
	"Gaming",
];
